# Generated by Django 4.0.6 on 2022-10-03 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='bool',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 20, 36, 11, 668276)),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='float',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 3, 20, 36, 11, 668327)),
        ),
    ]
