# Generated by Django 4.0.6 on 2022-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato_products', '0001_initial'),
        ('tomato_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='products',
            field=models.ManyToManyField(to='tomato_products.product'),
        ),
    ]
